<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
  /**
  * @var String $name
  * @return Item
  */
  public function add($name)
  {
    $item=new Item($name);
    $em=$this->getEntityManager();
    $em->persist($item);
    $em->flush();

    return $item;
  }
}
